sudo: false
language: cpp
compiler:
  - gcc
  - clang
env:
  - TOOL=autoconf
  - TOOL=cmake
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
script:
  - if [ "$TOOL" = "autoconf" ]; then autoconf && ./configure && make && make test && make valgrind-test; fi
  - if [ "$TOOL" = "cmake" ]; then mkdir build && cd build && cmake .. && ctest -D ExperimentalBuild && ctest -D ExperimentalMemCheck; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - gcc-4.7
            - g++-4.7
            - valgrind
            - cmake
