language: cpp
compiler:
  - gcc
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
  - wget "https://googlemock.googlecode.com/files/gmock-1.7.0.zip"
  - unzip gmock-1.7.0.zip
  - sudo apt-get install valgrind
script:
  - autoconf
  - ./configure --with-gmock=gmock-1.7.0
  - make
  - make test
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.7
            - g++-4.7
